# Generated by Django 4.2.23 on 2025-08-13 14:50

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                (
                    "file",
                    models.FileField(
                        upload_to=files.models.get_file_path, verbose_name="文件"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("video", "视频"), ("pdf", "PDF"), ("other", "其他")],
                        max_length=10,
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小(字节)"),
                ),
            ],
            options={
                "verbose_name": "媒体文件",
                "verbose_name_plural": "媒体文件",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
