# Generated by Django 4.2.23 on 2025-08-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="file_type",
            field=models.CharField(
                choices=[("video", "视频"), ("pdf", "PDF"), ("other", "其他")],
                default="other",
                max_length=10,
                verbose_name="文件类型",
            ),
        ),
    ]
