# Generated by Django 4.2.23 on 2025-08-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_images/"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple", "Single Choice"),
                    ("multiple_choice", "Multiple Choice"),
                    ("fill", "Fill in the Blank"),
                    ("essay", "Essay"),
                ],
                max_length=15,
            ),
        ),
    ]
