# Generated by Django 4.2.23 on 2025-08-24 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0002_question_image_alter_question_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AddField(
            model_name="exam",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(max_length=20, unique=True, verbose_name="学号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="电话"),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="院系"),
                ),
                (
                    "major",
                    models.CharField(blank=True, max_length=100, verbose_name="专业"),
                ),
                (
                    "grade",
                    models.CharField(blank=True, max_length=20, verbose_name="年级"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "学员",
                "verbose_name_plural": "学员",
            },
        ),
        migrations.CreateModel(
            name="ExamStudentAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分配人",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="exams.exam",
                        verbose_name="试卷",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_assignments",
                        to="exams.student",
                        verbose_name="学员",
                    ),
                ),
            ],
            options={
                "verbose_name": "试卷分配",
                "verbose_name_plural": "试卷分配",
                "unique_together": {("exam", "student")},
            },
        ),
    ]
