# Generated by Django 4.2.7 on 2025-09-10 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0003_exam_end_time_exam_is_active_exam_start_time_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'verbose_name': '学员答案', 'verbose_name_plural': '学员答案'},
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='答题时间'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('student', 'question')},
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学员')),
            ],
            options={
                'verbose_name': '考试会话',
                'verbose_name_plural': '考试会话',
            },
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0, verbose_name='总分')),
                ('max_score', models.FloatField(default=0, verbose_name='满分')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('is_completed', models.BooleanField(default=True, verbose_name='是否完成')),
                ('time_spent', models.IntegerField(default=0, verbose_name='用时(秒)')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学员')),
            ],
            options={
                'verbose_name': '考试提交记录',
                'verbose_name_plural': '考试提交记录',
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
